server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7070
  servlet:
    context-path: /
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml
